steps:
  - label: ":python: Test"
    commands:
      - python3 -m venv .venv
      - . .venv/bin/activate
      - pip install -r requirements.txt
      - pytest -q
    agents:
      queue: "default"

  - wait

  - label: ":docker: Build & Push Image"
    key: "build_push"
    commands:
  #    - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "mpdafa/buildkite-python:$BUILDKITE_COMMIT" .
      - docker push "mpdafa/buildkite-python:$BUILDKITE_COMMIT"
      - docker tag "mpdafa/buildkite-python:$BUILDKITE_COMMIT" "mpdafa/buildkite-python:latest"
      - docker push "mpdafa/buildkite-python:latest"
    agents:
      queue: "default"

  - block: ":warning: Deploy to production?"
    branches: "main"

  - label: ":rocket: Deploy (SSH)"
    key: "deploy"
    branches: "main"
    commands:
      - .buildkite/deploy.sh
    agents:
      queue: "default"
