steps:
  - label: ":python: Test (Docker Python)"
    key: "test"
    commands:
      - docker run --rm -v "$PWD:/app" -w /app python:3.12-slim bash -lc "
          python -m venv .venv &&
          . .venv/bin/activate &&
          pip install -U pip &&
          pip install -r requirements.txt &&
          pytest -q
        "
    agents:
      queue: "default"

  - wait

  - label: ":docker: Build & Push Image"
    key: "build_push"
    commands:
      - echo "$DOCKER_PASSWORD" | docker login "$DOCKER_REGISTRY" -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$DOCKER_IMAGE:$BUILDKITE_COMMIT" .
      - docker push "$DOCKER_IMAGE:$BUILDKITE_COMMIT"
      - docker tag "$DOCKER_IMAGE:$BUILDKITE_COMMIT" "$DOCKER_IMAGE:latest"
      - docker push "$DOCKER_IMAGE:latest"
    agents:
      queue: "default"

  - block: ":warning: Deploy to production?"
    branches: "main"

  - label: ":rocket: Deploy (SSH)"
    key: "deploy"
    branches: "main"
    commands:
      - .buildkite/deploy.sh
    agents:
      queue: "default"
